module SrcMD

using FileTrees
using Mustache

"map file extensions to Markdown code fence block annotation languages"
const ext_lang = (
    sh = "bash",
    c = "c",
    cpp = "cpp",
    cs = "csharp",
    css = "css",
    go = "go",
    html = "html",
    java = "java",
    js = "javascript",
    json = "json",
    jsx = "jsx",
    jl = "julia",
    kt = "kotlin",
    tex = "latex",
    md = "markdown",
    php = "php",
    txt = "plaintext",
    ps1 = "powershell",
    py = "python",
    r = "r",
    rb = "ruby",
    rs = "rust",
    sql = "sql",
    swift = "swift",
    ts = "typescript",
    tsx = "tsx",
    xml = "xml",
    yml = "yaml",
    apacheconf = "apache",
    coffee = "coffeescript",
    dart = "dart",
    djt = "django",
    erb = "erb",
    haml = "haml",
    http = "http",
    less = "less",
    nginxconf = "nginx",
    sass = "sass",
    scss = "scss",
    svelte = "svelte",
    vue = "vue",
    wasm = "wasm",
    clj = "clojure",
    cr = "crystal",
    d = "d",
    ex = "elixir",
    erl = "erlang",
    f90 = "fortran",
    fs = "fsharp",
    groovy = "groovy",
    hs = "haskell",
    lisp = "lisp",
    lua = "lua",
    m = "matlab",
    ml = "ocaml",
    pas = "pascal",
    pl = "perl",
    rkt = "racket",
    scala = "scala",
    scm = "scheme",
    tcl = "tcl",
    v = "vlang",
    vala = "vala",
    vb = "vbnet",
    zig = "zig",
    dockerfile = "dockerfile",
    env = "dotenv",
    git = "git",
    glsl = "glsl",
    graphql = "graphql",
    hcl = "hcl",
    ini = "ini",
    jenkinsfile = "jenkins",
    mak = "makefile",
    properties = "properties",
    proto = "protobuf",
    pp = "puppet",
    tf = "terraform",
    toml = "toml",
    vim = "vim"
)


end # module SrcMD
